# SPDX-FileCopyrightText: 2022 Technology Innovation Institute (TII)
#
# SPDX-License-Identifier: Apache-2.0

language: python
dist: focal
addons:
  apt:
    packages:
      - graphviz
python:
  - 3.8
install:
  # Install nix:
  - sh <(curl -L https://nixos.org/nix/install) --daemon --yes
  # Test nix-build:
  - source /etc/profile.d/nix.sh
  - nix-build '<nixpkgs>' -A hello
  # Install python requirements:
  - pip3 install -r requirements.txt
script:
  # Ensure 'test-ci' targets pass:
  - make test-ci
