# SPDX-FileCopyrightText: 2026 Technology Innovation Institute (TII)
#
# SPDX-License-Identifier: Apache-2.0

"""Shared DataFrame column names used across package boundaries."""

COMMENT = "comment"
COUNT = "count"
CPE = "cpe"
CLASSIFY = "classify"
DEPENDENCY_UID = "dependency_uid"
LEVEL = "level"
MODIFIED = "modified"
NAME = "name"
NEWEST_UPSTREAM_RELEASE = "newest_upstream_release"
NIXPKGS_PR = "nixpkgs_pr"
OUTPUTS = "outputs"
PACKAGE = "package"
PACKAGE_REPOLOGY = "package_repology"
PATCHED = "patched"
PNAME = "pname"
POTENTIALLY_VULNERABLE = "potentially_vulnerable"
RAW_NAME = "raw_name"
REPO = "repo"
REPO_VERSION_CLASSIFY = "repo_version_classify"
SBOM_VERSION_CLASSIFY = "sbom_version_classify"
SCANNER = "scanner"
SEVERITY = "severity"
SIMILARITY = "similarity"
SORTCOL = "sortcol"
SRC_PATH = "src_path"
STATUS = "status"
STORE_PATH = "store_path"
SUM = "sum"
TARGET_PATH = "target_path"
URL = "url"
VERSION = "version"
VERSION_CMP = "version_cmp"
VERSION_LOCAL = "version_local"
VERSION_NIXPKGS = "version_nixpkgs"
VERSION_REPOLOGY = "version_repology"
VERSION_SBOM = "version_sbom"
VERSION_UPSTREAM = "version_upstream"
VULN_ID = "vuln_id"
WHITELIST = "whitelist"
WHITELIST_COMMENT = "whitelist_comment"
